name: deploy_staging
on:
  push:
    branches:
      master

jobs:
  deploy:
    environment: staging

    steps:
      - name: Run
        runs-on: ubuntu-20.04
        run: echo "Deploying to staging!"
