name: deploy_staging
on:
  workflow_dispatch:  # manual trigger
  push:
    branches:
      master

jobs:
  deploy:
    environment: staging
    runs-on: ubuntu-20.04
    steps:
      - name: Run
        run: echo "Deploying to staging!"
